# -*- coding: utf-8 -*-
"""basic flask app for rfc chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LIySHVeh5Erzhp8f3Rs_PylG5cwnn3PA
"""

!pip install flask_ngrok
!pip install pyngrok==4.1.1
!ngrok authtoken 2XECznnbav3bq5ItE2sht9FxCgr_26Pg16gXwoNVtoC4YwCVN

from flask.templating import render_template
from flask import Flask, render_template, request, jsonify

from flask_ngrok import run_with_ngrok

from google.colab import drive
drive.mount('/content/gdrive')

template_folder = '/content/gdrive/MyDrive/AI-ML/chatbotapp/template/'
app = Flask(__name__, template_folder=template_folder)
run_with_ngrok(app)
# Initialize user_prompt variable
user_prompt = ""
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/set_prompt', methods=['POST'])
def set_prompt():
    global user_prompt
    user_prompt = request.json['user_input']
    print('user prompt:', user_prompt)
    return jsonify({'message': 'User prompt is set.'})

@app.route('/get_prompt', methods=['GET'])
def get_prompt():
    return jsonify({'user_prompt': user_prompt})


if __name__ == '__main__':
    app.run()